version: "3.7"

services:
    install:
        image: node:14
        command: sh -c "yarn install"
        working_dir: /app
        volumes:
            - ./:/app
    client:
        image: node:14
        command: sh -c "npm run client:dev"
        working_dir: /app
        ports:
            - 3000:3000
        volumes:
            - ./:/app
        tty: true
    build:
        image: node:14
        command: sh -c "npm run client:build"
        working_dir: /app
        volumes:
            - ./:/app
    deploy:
        image: node:14
        command: sh -c "npm run docker:deploy"
        working_dir: /app
        volumes:
            - ./:/app
    S3:
       image: amazon/aws-cli:latest
       tty: true
       command:  s3 sync /app/build/ s3://staging2.behodler
       volumes:
        - ./:/app
        - ~/.aws:/root/.aws
