export const WALLET_FRIENDLY_HOVER = 'WALLET_FRIENDLY_HOVER';
export type WALLET_FRIENDLY_HOVER = typeof WALLET_FRIENDLY_HOVER;

export const WALLET_FRIENDLY_PENCIL_CLICK = 'WALLET_FRIENDLY_PENCIL_CLICK';
export type WALLET_FRIENDLY_PENCIL_CLICK = typeof WALLET_FRIENDLY_PENCIL_CLICK;

export const WALLET_FRIENDLY_EDITOR_TEXTCHANGED = 'WALLET_FRIENDLY_EDITOR_TEXTCHANGED';
export type WALLET_FRIENDLY_EDITOR_TEXTCHANGED = typeof WALLET_FRIENDLY_EDITOR_TEXTCHANGED;

export const WALLET_FRIENDLY_EDITOR_CANCEL = 'WALLET_FRIENDLY_EDITOR_CANCEL';
export type WALLET_FRIENDLY_EDITOR_CANCEL = typeof WALLET_FRIENDLY_EDITOR_CANCEL;

export const WALLET_FRIENDLY_EDITOR_ACCEPT = 'WALLET_FRIENDLY_EDITOR_ACCEPT';
export type WALLET_FRIENDLY_EDITOR_ACCEPT = typeof WALLET_FRIENDLY_EDITOR_ACCEPT;






