import One from '../../../../images/behodler/1.png'
import Two from '../../../../images/behodler/2.png'
import Three from '../../../../images/behodler/3.png'
import Four from '../../../../images/behodler/4.png'
import Five from '../../../../images/behodler/5.png'
import Six from '../../../../images/behodler/6.png'
import Seven from '../../../../images/behodler/7.png'
// import Eight from '../../../../images/behodler/8.png'
import Nine from '../../../../images/behodler/9.png'
// import Ten from '../../../../images/behodler/10.png'
import Dai from '../../../../images/dai.png'
import eyedai from '../../../../images/behodler/eyedai.png'
import scxeth from '../../../../images/behodler/scxeth.png'
import scxeye from '../../../../images/behodler/scxeye.png'
import eye from '../../../../images/behodler_b.png'
import monster from '../../../../images/new/MonsterGun5.png'
import swapping from '../../../../images/new/animation.mp4'
import flippyArrows from '../../../../images/new/flippyArrows.png'
export const Images = [One, Two, Three, Four, Five, Six, Seven/* Eight*/, Nine, /*Ten*/  Dai, eye,eyedai, scxeth, scxeye,monster,flippyArrows,swapping]