export const CONNECT_TO_METAMASK = 'CONNECT_TO_METAMASK'
export type CONNECT_TO_METAMASK = typeof CONNECT_TO_METAMASK

export const SET_METAMASK_ENABLED = 'SET_METAMASK_ENABLED'
export type SET_METAMASK_ENABLED = typeof SET_METAMASK_ENABLED

export const SET_METAMASK_CONNECTED = 'SET_METAMASK_CONNECTED'
export type SET_METAMASK_CONNECTED = typeof SET_METAMASK_CONNECTED